### ISSUE TITLE
Why is there a CPP file?

### ISSUE THREAD

**Issue by pkeroulas** [stoth68000/libklvanc#57]
Hello,

I'd like to evaluate the integration of this library+tools in our [SMPTE ST2110 analyser](https://tech.ebu.ch/list). When using CMake, I get errors which leads me to this question: is there any particular reason why `tools/parse.cpp` is a C++ file, the only one?

I have a patch which turns it into a C file if you're interested.

PK

**Comment by pkeroulas** [comment]
@dheitmueller, any thought?

**Comment by dheitmueller** [comment]
Hi Patrick,

The "tools" directory isn't really intended to be part of the library itself.  It's mostly oriented around miscellaneous utilities which exercise the library (for demonstration purposes, testing, etc).

The file in question was in C++ because it was derived from a utility which interacts with the Blackmagic Decklink SDK, which requires C++.  Those such utilities has been moved to the klvanc-tools project though.

I wouldn't object to a patch which converts the utility to C assuming if the conversion was pretty clean.  Doing such would drop the C++ compiler requirement for building libklvanc, which is probably a good thing.
