### ISSUE TITLE
klvanc_context_destroy should destroy packets held in scte104_fragments

### ISSUE THREAD

**Issue by MathieuDuponchelle** [stoth68000/libklvanc#72]
As the title says :)

**Comment by dheitmueller** [comment]
Yeah, this looks like a legitimate issue.  The klvanc_context_destroy() should be calling the messageFragmentReset() routine in core-packet-scte104.c (although that's currently defined static so we might want a wrapper function).

I'm guessing it doesn't leak with the existing scte-104 fragment test vector we have in tools because the fragments get flushed out at the end of every successful packet.  Because the test case is a complete packet, we don't have any partial fragments to leak when the context is destroyed.

Thanks for reporting.

**Comment by dheitmueller** [comment]
The fix for this has been added to the following pull request.  Once that is merged this bug can be closed.

https://github.com/stoth68000/libklvanc/pull/79

**Comment by stoth68000** [comment]
Fixed. Thanks Devin.

**Comment by stoth68000** [comment]
Should be addressed. Feel free to re-open the issues if you think it hasn't been resolved.
